name: style
description: package for app styling
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.3.3"
  flutter: ">=3.0.0"

dependencies:
  flutter_staggered_grid_view: 0.6.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  gap: 2.0.1
  sliver_tools: 0.2.9
  flutter_svg: ^1.0.1
  tap_builder: 0.4.1
  flag: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/img/
    - google_fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: google_fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: google_fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Montserrat-Light.ttf
          weight: 300
        - asset: google_fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: google_fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: google_fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: google_fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Montserrat-Black.ttf
          weight: 900
#  uses-material-design: true

#flutter_intl:
#  enabled: true
