name: style
description: package for app styling
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_staggered_grid_view: 0.6.2
  equatable: 2.0.3
  flutter:
    sdk: flutter
  gap: 2.0.0
  sliver_tools: 0.2.7
  flutter_svg: ^1.1.1+1
  tap_builder: 0.3.4
  google_fonts: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/img/
    - google_fonts/
#  uses-material-design: true

#flutter_intl:
#  enabled: true